services:
  database:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    container_name: infrastructure-db
    environment:
      POSTGRES_DB: infrastructure_training
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d infrastructure_training" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  redis:
    image: redis:8.2.0-alpine
    container_name: infrastructure-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 3s
      retries: 3

  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile
    container_name: infrastructure-app
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: infrastructure_training
      PORT: 8080
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  app-network:
    driver: bridge